Trending/urls.py
from django.urls import path
from . import views

app_name = 'Trending'

urlpatterns = [
    path('', views.index, name='index'),
    path('topics',views.topics, name='topics'),
    path('about',views.about,name='about'),
    path('topics/<int:id>',views.detail ,name='detail')
]

twitter_sentiments/urls.py
from django.contrib import admin
from django.urls import path,include
from Trending import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Trending/', include('Trending.urls')),
    path('',views.index),
]

Trending/models.py
from django.db import models

# Create your models here.

Trending/views.py
from django.shortcuts import render
import plotly
import plotly.tools as tls
import matplotlib.pyplot as plt
import matplotlib
matplotlib.use('Agg')
from . import graphs
List = graphs.topics


def index(request):
    context = {'fig2': graphs.bargraph,'fig1':graphs.india,'fig3':graphs.piechrat}
    return render(request, 'Trending/index.html',context)


def topics(request):
    context ={'context':List}
    return render(request,'Trending/topics.html', context)


def about(request):
    fig, ax = plt.subplots()
    ax.plot([1, 3, 4], [3, 2, 5])
    plotly_fig = tls.mpl_to_plotly(fig)
    graph_div = plotly.offline.plot(plotly_fig, auto_open=False, output_type="div")
    return render(request,'Trending/about.html', {'fig':graph_div})


def detail(request, id):
    topic = List[id-1][0]
    context = graphs.topic_graph(topic)
    context['topic'] = topic
    return render(request,'Trending/detail.html',context)

Trending/templates/Trending/about.html
{% extends 'Trending/base.html' %}

{% block title %}About{% endblock %}

{% block about_active %}active{% endblock %}


{% block body %}
{% load static %}

	<section class="hero-wrap hero-wrap-2" style="background-image: url('{% static 'Trending/images/bg_2.jpg' %}');" data-stellar-background-ratio="0.5">
	<div class="overlay"><!--remove this--></div>
    <div class="container">
        <div class="row no-gutters slider-text align-items-end justify-content-center">
          <div class="col-md-9 ftco-animate pb-5 text-center">
            <h1 class="mb-3 bread">About Us</h1>
            <p class="breadcrumbs">
				<span class="mr-2">
				<a href="{% url 'Trending:index' %}">Home <i class="ion-ios-arrow-forward"></i></a>
				</span>
				<span>About us <i class="ion-ios-arrow-forward"></i></span>
			</p>
          </div>
        </div>
      </div><!--remove this-->

</section>

	<section class="ftco-section ftco-no-pt ftco-no-pb bg-light">
    	<div class="container">
    		<div class="row d-flex">
    			<div class="col-md-6 d-flex">
    				<div class="img img-video d-flex align-self-stretch align-items-center justify-content-center justify-content-md-end" style="background-image:url('{% static 'Trending/images/about.jpg' %}');">
    					<a href="#" class="icon-video d-flex justify-content-center align-items-center">
    						<span class="icon-play"></span>
    					</a>
    				</div>
    			</div>
    			<div class="col-md-6 pl-md-5">
    				<div class="row justify-content-start py-5">
		          <div class="col-md-12 heading-section ftco-animate">
		            <h2 class="mb-4">Welcome to Twitter Sentiments</h2>
		            <p>contextual mining of text which identifies and extracts subjective information in source material, and helping a business to understand the social sentiment of their brand, product or service while monitoring online conversations.</p>
					  <span class="subheading">Tools Used</span>
		            <div class="services-wrap">
		            	<a href="https://www.djangoproject.com/start/overview/" class="services-list">Django
		            		<div class="btn-custom d-flex align-items-center justify-content-center"><span class="ion-ios-arrow-round-forward"></span></div>
		            	</a>
		            	<a href="https://developers.google.com/apis-explorer" class="services-list">Google Api
		            		<div class="btn-custom d-flex align-items-center justify-content-center"><span class="ion-ios-arrow-round-forward"></span></div>
		            	</a>
		            	<a href="https://developer.twitter.com/en/docs" class="services-list">Twitter Api
		            		<div class="btn-custom d-flex align-items-center justify-content-center"><span class="ion-ios-arrow-round-forward"></span></div>
		            	</a>
		            	<a href="https://matplotlib.org/" class="services-list">Data Visualisation
		            		<div class="btn-custom d-flex align-items-center justify-content-center"><span class="ion-ios-arrow-round-forward"></span></div>
		            	</a>
		            	<a href="https://textblob.readthedocs.io/en/dev/" class="services-list">Sentiment Analysis
		            		<div class="btn-custom d-flex align-items-center justify-content-center"><span class="ion-ios-arrow-round-forward"></span></div>
		            	</a>
		            </div>
		          </div>
		        </div>
	        </div>
        </div>
    	</div>
    </section>

{% endblock %}

<!-- works fine
<div class="container" style="width:100;height:100">
    {{ fig|safe }}
</div>
-->

Trending/templates/Trending/base.html
<!DOCTYPE html>
<html lang="en">
{% load static  %}
<head>
    <title>{% block title %}Title{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">


    <link rel="stylesheet" href="{% static 'Trending/css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'Trending/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'Trending/css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'Trending/css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'Trending/css/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'Trending/css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'Trending/css/icomoon.css' %}">
    <link rel="stylesheet" href="{% static 'Trending/css/style.css' %}">

</head>
<body ><!--style="background-image:url({% static 'Trending/images/back.jpg' %});">-->

    <!--heading-->
    <div class="container pt-5 pb-4">
			<div class="row justify-content-between">
				<div class="col-md-8 order-md-last">
					<div class="row">
						<div class="col-md-6 text-center">
							<a class="navbar-brand" href="http://127.0.0.1:8000/">Twitter<span>Sentiments</span></a>
						</div>
					</div>
				</div>
				<div class="col-md-4 d-flex">
					<div class="social-media">
		    		<p class="mb-0 d-flex">
		    			<a href="https://twitter.com/Abhishekvaish40" class="d-flex align-items-center justify-content-center"><span class="fa fa-twitter"><i class="sr-only">Twitter</i></span></a>
		    			<a href="https://github.com/Abhishekvaish?tab=repositories" class="d-flex align-items-center justify-content-center"><span class="fa fa-github"><i class="sr-only">Github</i></span></a>
                        <a href="https://www.linkedin.com/in/abhishek-vaish-b3195817a/" class="d-flex align-items-center justify-content-center"><span class="fa fa-linkedin"><i class="sr-only">Instagram</i></span></a>
		    		</p>
	        </div>
				</div>
			</div>
		</div>

    <!--navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
	    <div class="container-fluid">

	      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="fa fa-bars"></span> Menu
	      </button>
	      <div class="collapse navbar-collapse" id="ftco-nav">
	        <ul class="navbar-nav m-auto">
	        	<li class="nav-item {% block home_active %}{% endblock %}"><a href="{% url 'Trending:index' %}" class="nav-link">Home</a></li>
	        	<li class="nav-item {% block topics_active %}{% endblock %}"><a href="{% url 'Trending:topics' %}" class="nav-link">Topics</a></li>
                <li class="nav-item {% block about_active %}{% endblock %}"><a href="{% url 'Trending:about' %}" class="nav-link">About</a></li>

	        </ul>
	      </div>
	    </div>
	  </nav>


    {% block body %}

    {% endblock %}

    <section class="ftco-intro bg-primary py-5">
			<div class="container">
				<div class="row justify-content-between align-items-center">
					<div class="col-md-6">
						<h2>Contact with us</h2>
						<p>Do you have any comments or questions about the products?<br/> then contact us.</p>
					</div>
					<div class="col-md-5 text-md-right">
						<span class="contact-number">+91 (829) 188-05-62 </span>
                        <span class="contact-number">+91 (810) 409-61-86</span>
					</div>
				</div>
			</div>
		</section>
    <footer class="ftco-footer ftco-bg-dark ftco-section">
      <div class="container">
        <div class="row mb-5">
          <div class="col-md-6 col-lg">
            <div class="ftco-footer-widget mb-4">
              <h2 class="logo"><a href="#">Twitter <span>Sentiments</span></a></h2>
              <p>computationally identifying and categorizing opinions expressed in a piece of text, especially in order to determine whether the writer's attitude towards a particular topic, product, etc. is positive, negative, or neutral.</p>
              <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                <li class="ftco-animate"><a href="https://twitter.com/thakerrahul16"><span class="icon-twitter"></span></a></li>
                <li class="ftco-animate"><a href="https://github.com/rahulthaker?tab=repositories"><span class="icon-github"></span></a></li>
                <li class="ftco-animate"><a href="https://www.linkedin.com/in/rahul-t-634946141/"><span class="icon-linkedin"></span></a></li>
              </ul>
            </div>
          </div>
          <div class="col-md-6 col-lg">
            <div class="ftco-footer-widget mb-4">
            	<h2 class="ftco-heading-2">Contact information</h2>
            	<div class="block-23 mb-3">
	              <ul>
	                  <li><span class="icon icon-map-marker"></span><span class="text">KJ Somaiya Institute of Engineering and Information Technology</span></li>
	                  <li><a href="#"><span class="icon icon-phone"></span><span class="text">+91 (829) 188-05-62<br/>+91 (810) 409-61-86</span></a></li>
	                  <li><a href="#"><span class="icon icon-envelope"></span><span class="text">abhishek.vaish@somaiya.edu <br/>rahul.thaker@somaiya.edu</span></a></li>

	              </ul>
	            </div>
            </div>
          </div>

        </div>
        <div class="row">
          <div class="col-md-12 text-center">

            <p>
                Copyright &copy;<script>document.write(new Date().getFullYear());</script>
                All rights reserved | This website is made with <i class="icon-heart color-danger" aria-hidden="true"></i>
                <a href="https://www.djangoproject.com/start/overview/" target="_blank">Django</a>
            </p>
          </div>
        </div>
      </div>
    </footer>

    <!-- loader -->
    <div id="ftco-loader" class="show fullscreen">
        <svg class="circular" width="48px" height="48px">
            <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
            <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/>
        </svg>
    </div>

    <script src="{% static 'Trending/js/jquery.min.js' %}"></script>
    <script src="{% static 'Trending/js/jquery-migrate-3.0.1.min.js' %}"></script>
    <script src="{% static 'Trending/js/popper.min.js' %}"></script>
    <script src="{% static 'Trending/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'Trending/js/jquery.easing.1.3.js' %}"></script>
    <script src="{% static 'Trending/js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'Trending/js/jquery.stellar.min.js' %}"></script>
    <script src="{% static 'Trending/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'Trending/js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'Trending/js/scrollax.min.js' %}"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
    <script src="{% static 'Trending/js/google-map.js' %}"></script>
    <script src="{% static 'Trending/js/main.js' %}"></script>

</body>
</html>

Trending/templates/Trending/detail.html
{% extends 'Trending/base.html' %}
{% block title %}{{topic}}{% endblock %}

{% block body %}
{% load static %}
<section class="hero-wrap hero-wrap-2" style="background-image: url(data:image/png;base64,{{fig1|safe}}); background-position: 50% -7px;" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text align-items-end justify-content-center">
          <div class="col-md-9 ftco-animate pb-5 text-center fadeInUp ftco-animated">
            <h1 class="mb-3 bread">{{topic}}</h1>
            <p class="breadcrumbs"><span class="mr-2"><a href={% url 'Trending:topics' %}>All Topics <i class="ion-ios-arrow-forward"></i></a></span> <span>{{topic}} <i class="ion-ios-arrow-forward"></i></span></p>
          </div>
        </div>
      </div>
    </section>
<br/><br/>

<section class="ftco-section ftco-no-pt ftco-no-pb">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 py-5 order-md-last">
                 <div class="heading-section ftco-animate">
                    <span class="subheading">Hashtag</span>
                    <h2 class="mb-4">Sentiments </h2>
                    <p>Interpretation and classification of emotions (positive, negative and neutral) within text data using text analysis techniques.<br/>Sentiment analysis allows us to identify sentiment toward products, brands, services in online conversations and feedback.</p>
                    <p><a href="https://www.lexalytics.com/technology/sentiment-analysis" class="btn btn-primary py-3 px-4">Know More</a></p>
              </div>
            </div>
            <div class="col-lg-8 services-wrap px-4 pt-5">
                <div class="row pt-md-3">
                    <img src="data:image/png;base64,{{fig2|safe}}" width="700" ><!--style="border:2px solid black ;">-->
                </div>
            </div>
        </div>
    </div>
</section>
<br/><br/>

<div class="hero-wrap js-fullheight" style="background-image: url({% static 'Trending/images/back2.jpg' %}); height: 560px; background-position: 50% 134.744px;" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-center justify-content-start" data-scrollax-parent="true" style="height: 560px;">
            <div class="col-md-6 ftco-animate fadeInUp ftco-animated">
          	    <h2 class="subheading">Sentiment Analysis Result</h2>
              	<h1>Polarity for <br/>{{topic}} </h1>
                <p class="mb-4">Based on tweets</p>
                <p><a href="https://scholar.google.co.in/scholar?q=polarity+sentiment+analysis&hl=en&as_sdt=0&as_vis=1&oi=scholart" class="btn btn-primary mr-md-4 py-2 px-4">Learn more <span class="ion-ios-arrow-forward"></span></a></p>
              </div>
            <div class="col-md-6 ftco-animate fadeInUp ftco-animated">
                <img src="data:image/png;base64,{{fig3|safe}}" width="600" style="border-radius: 30px;">
            </div>
        </div>
      </div>
</div>
<br/><br/>


<div class="col-md-12 text-center heading-section ftco-animate fadeInUp ftco-animated">
        <span class="subheading">In last 24-hours</span>
        <h2 class="mb-4">Frequency of Tweets </h2>
</div>
<div class="container" style="border:5px solid black">
        <div class="row">
        <div class="col-lg-6 py-5">
            <div class="heading-section ftco-animate">
	          	<span class="subheading">{{topic}}</span>
	            <h2 class="mb-4">Timeline </h2>
                <p>Sentiment analysis is a vital topic in the field of NLP. It has easily become one of the hottest topics in the field because of its relevance and the number of business problems it is solving and has been able to answer.</p>
                <p>The bargraph of number of tweets v/s hour here shows the activity of people related to {{topic}} throughtout the day .</p>
	            <p><a href="https://google.com/search?q={{topic}}" class="btn btn-primary py-3 px-4">Get a Quote</a></p>
	          </div>
        </div>
        <div class="col-lg-6 py-5">
            <img src="data:image/png;base64,{{fig4|safe}}" width="600">
        </div>
    </div>
</div>

<br/><br/>

{% endblock %}

Trending/templates/Trending/index.html
{% extends 'Trending/base.html' %}

{% block title %}Trending{% endblock %}


{% block home_active %}active{% endblock %}

{% block body %}
{% load static %}
    <section class="ftco-section ftco-no-pt ftco-no-pb">
    	<div class="container">
    		<div class="row">
    			<div class="col-lg-4 py-5 order-md-last">
	                 <div class="heading-section ftco-animate">
        	          	<span class="subheading">WordCloud</span>
        	            <h2 class="mb-4">India Today</h2>
        	            <p>A word cloud (also known as tag cloud or text cloud) is a visual representation of word frequency and value. It is used to highlight how often a specific term or category appears in a source of data. The more times a keyword is present in a data set, the bigger and bolder the keyword appears.</p>
                         <p>This WordCloud gives us a visual Respresentation of the text, words used by people  in which the frequency of word varies directly with the size.</p>
        	            <p><a href="https://amueller.github.io/word_cloud/" class="btn btn-primary py-3 px-4">Learn More</a></p>
    	          </div>
    			</div>
    			<div class="col-lg-8 services-wrap px-4 pt-5">
    				<div class="row pt-md-3">
                            <img src="data:image/png;base64,{{fig1|safe}}"/>
    				</div>
    			</div>
    		</div>
    	</div>
    </section>
    <br/><br/>

    <div class="container" style="border:5px solid black">
        <div class="row">
        <div class="col-lg-3 py-5">
            <div class="heading-section ftco-animate">
	          	<span class="subheading">Daily Trends</span>
	            <h2 class="mb-4">Trending Topics in India</h2>
	            <p>The bargraph here shows the Top 10 trending topics in India Today .</p>
	            <p><a href={% url 'Trending:topics' %} class="btn btn-primary py-3 px-4">All topics</a></p>
	          </div>
        </div>
        <div class="col-lg-9 py-5">
            <img src="data:image/png;base64,{{fig2|safe}}" style="border:2px solid black ;">
        </div>
    </div>

    </div>
    <br/><br/>

    <div class="hero-wrap js-fullheight" style="background-image: url({% static 'Trending/images/home1.jpg' %})" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-center justify-content-start" data-scrollax-parent="true">
            <div class="col-md-4 ftco-animate">
          	<h2 class="subheading">Welcome to Twitter Sentiments</h2>
          	<h1>Top Hashtag </h1>
            <p class="mb-4">In Last 24-hours</p>
            <p><a href="{% url 'Trending:topics' %}" class="btn btn-primary mr-md-4 py-2 px-4">Learn more <span class="ion-ios-arrow-forward"></span></a></p>
          </div>
            <div class="col-md-8 ftco-animate">
                <img src="data:image/png;base64,{{fig3|safe}}" style="border-radius: 30px;">
            </div>
        </div>
      </div>
    </div>
    <br/><br/>

{% endblock %}

Trending/templates/Trending/topics.html
{% extends 'Trending/base.html' %}

{% block title %}Trending Topics in India{% endblock %}


{% block topics_active %}active{% endblock %}

<!--style="background-color: #f5faf6;"-->
{% block body %}
{% load static %}
<section class="ftco-section ftco-no-pt"  style="background-image:url({% static 'Trending/images/back.jpg' %})">
    	<div class="container" >
    		<div class="row" >
    			<div class="col-lg-12 services-wrap px-4 pt-5">
                    <div class="row pt-md-3">
                    {% for topic,count in context  %}
						{% if count > 100 %}
	                        <a href="{% url 'Trending:detail' forloop.counter %}">
                            <div class="col-md-3 d-flex align-items-stretch">
		    				<div class="services text-center">
		    					<div class="icon d-flex justify-content-center align-items-center">
		    						<span class="flaticon-natural-resources"></span>
		    					</div>
		    					<div class="text">
		    						<h3>{{ topic }}</h3>
		    						<p>Over {{ count }} tweets </p>
		    					</div>
		    					<a href="{% url 'Trending:detail' forloop.counter %}" class="btn-custom d-flex align-items-center justify-content-center"><span class="ion-ios-arrow-round-forward"></span></a>
		    				</div>
		    			</div>
                        </a>
							{% if  forloop.counter|divisibleby:"4" %}
	                            </div><div class="row pt-md-3"></div><div class="row pt-md-3">
	                        {% endif %}
						{% endif %}
                    {% endfor  %}
                    </div>
                    <!--sample
    				<div class="row pt-md-3">
    					<div class="col-md-3 d-flex align-items-stretch">
		    				<div class="services text-center">
		    					<div class="icon d-flex justify-content-center align-items-center">
		    						<span class="flaticon-fence"></span>
		    					</div>
		    					<div class="text">
		    						<h3>Garden Care</h3>
		    						<p>Seeking justice in the world is a sed significant emotional and investment when we follow this call.</p>
		    					</div>
		    					<a href="#" class="btn-custom d-flex align-items-center justify-content-center"><span class="ion-ios-arrow-round-forward"></span></a>
		    				</div>
		    			</div>
		    			<div class="col-md-3 d-flex align-items-stretch">
		    				<div class="services text-center">
		    					<div class="icon d-flex justify-content-center align-items-center">
		    						<span class="flaticon-lawn-mower"></span>
		    					</div>
		    					<div class="text">
		    						<h3>Lawn mowing</h3>
		    						<p>Seeking justice in the world is a sed significant emotional and investment when we follow this call.</p>
		    					</div>
		    					<a href="#" class="btn-custom d-flex align-items-center justify-content-center"><span class="ion-ios-arrow-round-forward"></span></a>
		    				</div>
		    			</div>
		    			<div class="col-md-3 d-flex align-items-stretch">
		    				<div class="services text-center">
		    					<div class="icon d-flex justify-content-center align-items-center">
		    						<span class="flaticon-natural-resources"></span>
		    					</div>
		    					<div class="text">
		    						<h3>Lawn care</h3>
		    						<p>Seeking justice in the world is a sed significant emotional and investment when we follow this call.</p>
		    					</div>
		    					<a href="#" class="btn-custom d-flex align-items-center justify-content-center"><span class="ion-ios-arrow-round-forward"></span></a>
		    				</div>
		    			</div>
                        <div class="col-md-3 d-flex align-items-stretch">
		    				<div class="services text-center">
		    					<div class="icon d-flex justify-content-center align-items-center">
		    						<span class="flaticon-natural-resources"></span>
		    					</div>
		    					<div class="text">
		    						<h3>Lawn care</h3>
		    						<p>Seeking justice in the world is a sed significant emotional and investment when we follow this call.</p>
		    					</div>
		    					<a href="#" class="btn-custom d-flex align-items-center justify-content-center"><span class="ion-ios-arrow-round-forward"></span></a>
		    				</div>
		    			</div>
    				</div>
                    <div class="row pt-md-3"></div>
                    <div class="row pt-md-3">
    					<div class="col-md-3 d-flex align-items-stretch">
		    				<div class="services text-center">
		    					<div class="icon d-flex justify-content-center align-items-center">
		    						<span class="flaticon-fence"></span>
		    					</div>
		    					<div class="text">
		    						<h3>Garden Care</h3>
		    						<p>Seeking justice in the world is a sed significant emotional and investment when we follow this call.</p>
		    					</div>
		    					<a href="#" class="btn-custom d-flex align-items-center justify-content-center"><span class="ion-ios-arrow-round-forward"></span></a>
		    				</div>
		    			</div>
		    			<div class="col-md-3 d-flex align-items-stretch">
		    				<div class="services text-center">
		    					<div class="icon d-flex justify-content-center align-items-center">
		    						<span class="flaticon-lawn-mower"></span>
		    					</div>
		    					<div class="text">
		    						<h3>Lawn mowing</h3>
		    						<p>Seeking justice in the world is a sed significant emotional and investment when we follow this call.</p>
		    					</div>
		    					<a href="#" class="btn-custom d-flex align-items-center justify-content-center"><span class="ion-ios-arrow-round-forward"></span></a>
		    				</div>
		    			</div>
		    			<div class="col-md-3 d-flex align-items-stretch">
		    				<div class="services text-center">
		    					<div class="icon d-flex justify-content-center align-items-center">
		    						<span class="flaticon-natural-resources"></span>
		    					</div>
		    					<div class="text">
		    						<h3>Lawn care</h3>
		    						<p>Seeking justice in the world is a sed significant emotional and investment when we follow this call.</p>
		    					</div>
		    					<a href="#" class="btn-custom d-flex align-items-center justify-content-center"><span class="ion-ios-arrow-round-forward"></span></a>
		    				</div>
		    			</div>
    				</div>
    				-->
    			</div>
    		</div>
    	</div>
    </section>

{% endblock %}